app.config.ts, content/2.proxy/2.configuration.md, content/2.proxy/3.changelog.md, content/3.client/3.configuration.md, content/3.client/4.changelog.md
changes:
- update github link
- update meta description
- added turnstile key configuration reference (client & proxy)
- add missing changelogs for proxy and client
=> Turnstile docs

content/3.client/4.changelog.md, content/4.backend/2.configuration.md, content/4.backend/3.changelog.md
=> Backend v1.2.0 and client v1.4.1

content/3.client/4.changelog.md
=> Add new version to changelog

content/3.client/3.configuration.md, content/3.client/4.changelog.md
=> Update docs with 4.1.3

content/2.proxy/3.changelog.md, content/3.client/4.changelog.md
=> Update changelogs with new versions

content/2.proxy/1.deploy.md
Adds the instructions required for deploying the proxy to Netlify.
=> Add Netlify deployment method for hosting the proxy

content/2.proxy/1.deploy.md, content/4.backend/1.deploy.md
Add Railway deployment method for proxy and backend with `Deploy on Railway` buttons + instructions.
=> Add Railway deployment method for proxy and backend

content/3.client/3.configuration.md, content/3.client/4.changelog.md
changes:
- added changelog for v4.3.0
- added new configuration for client
=> V4.3.0 changes

content/3.client/4.changelog.md
=> changelog update for 4.3.1

content/3.client/3.configuration.md, content/3.client/4.changelog.md
=> Added new version v4.3.2 to docs

content/2.proxy/1.deploy.md, content/3.client/4.changelog.md
=> Add warnings for cloudflare and changelog for client 4.3.3

content/0.instances.md
Swap from Netlify to my own domain :)
=> docs: mv-web.netlify.app -> watch.qtchaos.de

content/0.instances.md
sort instances. 
[Related Discord Message](https://discord.com/channels/871713465100816424/871713465578979351/1213121106286878771)
=> Sort instances!

content/4.backend/1.deploy.md
Adding more in depth steps to selfhost, so we can see more community supported instances and later make a hub for them all? Future plans lmao. For now helps selfhosting, I debated whether to add a guide for reverse proxy and Cloudflare Argo tunneling, you guys can lmk! https://rentry.co/Movie-Web-Backend/ has the reverse proxy part in it.
=> More indepth steps for selfhosting backend

content/3.client/1.deploy.md
This PR is to add a 3rd option, `docker-compose` to client deployment.
=> Update client docs - 3rd option docker compose

content/0.instances.md
- Used real formatting with a note
- Added the other backend url
=> Real formatting

content/0.instances.md
[Discord message for context](https://discord.com/channels/871713465100816424/1212032514718310430/1214724373953515590)
=> Add pwa emojis to instances that support it

content/0.instances.md
Wasn't included in https://github.com/movie-web/docs/pull/50
=> Add PWA emoji to watch.qtchaos.de

content/0.instances.md
=> Set my profile to sudo-flix github

content/2.proxy/1.deploy.md
=> recommend netlify and fix link

content/5.extra/2.selfhost.md
Added a docker compose file that hosted all of movie-web, just to encourage more selfhosting and have a more straightforward way defined for people selfhosting.
=> Add a full self deployment docker file

content/0.instances.md, content/3.client/5.upgrade.md
in his own words
```
2024-03-30 7:36
---------------------------------
Toon: you removed the damn env line for the github token
Toon: just add that back to the action and ez fix
Toon: add bakc
```
=> Mr Toon Requested I Fix This

package.json, pnpm-lock.yaml
changes:
- Update Guider version, new update fixes table responsiveness.
=> Update Guider version

pages/client/deploy.mdx
This improved method 1 will ensure that the user's self-hosted instance will be up-to-date with the latest features and bug fixes if the user set it up correctly.
=> I Improved Method 1 to enable Automatic update of the user's Instance.

pages/instances.mdx
(old one will continue to work)
=> change bmov link

package.json, pnpm-lock.yaml
changes:
- update guider to latest version
=> Update Guider to v1.0.1
